import raw from "./spotify.json";

export type Artist = {
  id: string;
  name: string;
  image: string | null;
  genres: string[];
  url: string;
};

export type Track = {
  id: string;
  name: string;
  artists: string[];
  album: string;
  image: string | null;
  durationMs: number;
  url: string;
};

export type RangeKey = "short_term" | "medium_term" | "long_term";

export type SpotifyData = {
  /** ISO timestamp of the last successful sync, null in the committed snapshot. */
  generatedAt: string | null;
  profile: { name: string; url: string };
  ranges: Record<RangeKey, { artists: Artist[]; tracks: Track[] }>;
};

/**
 * Generated by `scripts/fetch_spotify.mjs` (`npm run spotify:sync`) and refreshed
 * in CI on every deploy. The committed file is a snapshot, so the page renders
 * an explicit empty state rather than stale invention when it has never run.
 */
export const spotify = raw as SpotifyData;

export const ranges: { key: RangeKey; label: string; caption: string }[] = [
  { key: "short_term", label: "Last month", caption: "the past four weeks" },
  { key: "medium_term", label: "Last 6 months", caption: "the past six months" },
  { key: "long_term", label: "All time", caption: "the past few years" },
];

export const hasData = ranges.some(
  ({ key }) => spotify.ranges[key].artists.length > 0 || spotify.ranges[key].tracks.length > 0,
);

export function formatDuration(ms: number): string {
  const totalSeconds = Math.round(ms / 1000);
  return `${Math.floor(totalSeconds / 60)}:${String(totalSeconds % 60).padStart(2, "0")}`;
}
